// Generated by CoffeeScript 1.6.3
(function() {
  var argv, command, createMiniHarp, path, port;

  createMiniHarp = require("../lib/index");

  argv = require("minimist")(process.argv.splice(2));

  port = argv.port || 4000;

  path = argv._[0] || process.cwd();

  command = function() {
    return createMiniHarp(path, port);
  };

  module.exports = command;

}).call(this);
