// Generated by CoffeeScript 1.6.3
(function() {
  var createMiniHarp;

  createMiniHarp = function(path, port) {
    var app, connect, serveStatic;
    connect = require("connect");
    serveStatic = require("serve-static");
    app = connect();
    return app.use(function(request, response, next) {
      var date, url;
      url = request.url;
      console.log(url);
      if (url === "/current-time") {
        date = (new Date()).toISOString();
        response.end(date + "\n");
      } else {
        next();
      }
    }).use(serveStatic(path)).listen(port);
  };

  module.exports = createMiniHarp;

}).call(this);
