// Generated by CoffeeScript 1.6.3
(function() {
  var createMiniHarp;

  createMiniHarp = function(path, port) {
    var app, connect, serveStatic;
    connect = require("connect");
    serveStatic = require("serve-static");
    app = connect();
    console.log("MiniHarp start at 4000...");
    return app.use(function(request, response, next) {
      var date;
      console.log(request.url);
      if (request.url === "/current-time") {
        date = (new Date()).toISOString();
        response.end(date + "\n");
      } else {
        next();
      }
    }).use(serveStatic(path)).listen(port);
  };

  module.exports = createMiniHarp;

}).call(this);
