// Generated by CoffeeScript 1.7.1
(function() {
  var createMiniHarp;

  createMiniHarp = function() {
    var app, connect;
    connect = require("connect");
    app = connect();
    return app;
  };

  module.exports = createMiniHarp;

}).call(this);
